[package]
name = "xtp-rs"
version = "0.1.0"
edition = "2024"

[features]
default = [ "geosite", "sniff-quic", "sniff-http", "sniff-tls" ]
# default = [ ]
geosite = ["dep:geosite-rs", "dep:prost"]
sniff-tls-common = []
sniff-quic = ["dep:aes", "dep:aes-gcm", "dep:hkdf", "dep:sha2", "sniff-tls-common"]
sniff-tls = ["sniff-tls-common"]
sniff-http = []

[dependencies]
tokio = { version = "1", features = ["full"] }
socket2 = { version = "0.6", features = ["all"] }
libc = "0.2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
maxminddb = { version = "0.28.1", features = ["simdutf8"] }
clap = { version = "4", features = ["derive"] }
serde = "1.0.228"
toml = "1.1.2"
tokio-util = "0.7.18"
anyhow = "1.0.102"
nix = { version = "0.31.3", features = ["net", "socket", "uio"] }
tokio-splice = "0.2.1"
ipnet = "2.12.0"
iptrie = "0.11.1"

# 以下仅在 sniff-quic 开启时才编译
sha2 = { version = "0.11.0", optional = true }
hkdf = { version = "0.13.0", optional = true }
aes = { version = "0.9.0", optional = true }
aes-gcm = { version = "0.11.0-rc.4", optional = true }
fastrand = "2.4.1"
serde_json = "1.0.149"
arc-swap = "1.9.1"
geosite-rs = { git = "https://github.com/hrimfaxi/geosite-rs.git", branch = "main", optional = true }
prost = { version = "0.14", optional = true }

[profile.release]
opt-level = "z"      # 比 "s" 更激进的体积优化
lto = true           # 全链接期优化
codegen-units = 1    # 单编译单元，让 LTO 效果最大化
strip = true         # 自动 strip
panic = "abort"      # 去掉 panic unwind 逻辑
