[target.mipsel-unknown-linux-musl]
linker = "mipsel-linux-muslsf-gcc"

[target.mips-unknown-linux-musl]
linker = "mips-linux-muslsf-gcc"

[target.mips64-unknown-linux-muslabi64]
linker = "mips64-linux-muslsf-gcc"

[target.mips64el-unknown-linux-muslabi64]
linker = "mips64el-linux-muslsf-gcc"
