#!/bin/sh /etc/rc.common

START=99 # 设置启动优先级，数字越大越晚启动
USE_PROCD=1
STARTUP_DELAY=10 # 延迟启动时间，可根据需要调整
start_service() {
  procd_open_instance
  # 如果 ujail 和 capabilities 配置存在，则启用沙盒保护
  if [ -x /sbin/ujail ] && [ -e /etc/capabilities/xtp-rs.json ]; then
    procd_add_jail xtp-rs ronly requirejail
    procd_set_param capabilities /etc/capabilities/xtp-rs.json
    procd_set_param user nobody
    procd_set_param group nobody
    procd_set_param no_new_privs 1
    procd_add_jail_mount /etc/xtp-rs
    procd_add_jail_mount /etc/tsubamegaeshi-rs
  fi
  procd_set_param env xtp-rs_LOCATION_ASSET="/usr/local/xtp-rs"
  procd_set_param limits nofile="1024768 1024768"
  procd_set_param command /usr/bin/xtp-rs -c /etc/xtp-rs/config.toml
  procd_set_param respawn 3600 5 0 # 设置自动重启
  procd_set_param stdout 1 # 启用日志输出
  procd_set_param stderr 1
  procd_close_instance
}
stop_service() {
  service_stop /usr/bin/xtp-rs
}

# vim: set sw=2 ts=2 et:
